import { useEffect, useMemo, useRef, useState } from "react";
import { Bell, Brain, Check, ChevronDown, CircleUserRound, Download, FileText, Heart, Lightbulb, Menu, Mic, Moon, Paperclip, Pause, Play, Send, ShieldCheck, Sparkles, Speaker, Square, Sun, Trash2, Volume2, X, Zap } from "lucide-react";
import AliceAvatar, { AliceStatusLegend, AliceStatusWaveform, type AliceStatus } from "./AliceAvatar";
import { lighthouseDiscoveryConfig as config } from "../../config/lighthouseDiscoveryConfig";
import { alicePromptProfiles, getAlicePromptProfile, isAlicePromptProfileId, type AlicePromptProfileId } from "../../config/alicePromptProfiles";
import "./discovery.css";

type Turn = { id: string; role: "participant" | "alice" | "system"; text: string; timestamp: string; inputMode: "typed" | "voice"; transcriptEdited: boolean; aliceVoiceEnabled: boolean; quietMode: boolean; aliceStatusAtTime: AliceStatus; audioUrl?: string; source: "chat" | "transcript" | "note" };
type Tab = "speak" | "type" | "attach";
const STORAGE_KEY = "lighthouse.discovery.run1";
const PROMPT_PROFILE_STORAGE_KEY = "lighthouse.discovery.alicePromptProfile";
const now = () => new Date().toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });
const seed: Turn[] = [{ id: "welcome", role: "alice", text: "To help me understand you deeply, what have been the moments in your life that changed the way you see yourself or the world?", timestamp: now(), inputMode: "typed", transcriptEdited: false, aliceVoiceEnabled: true, quietMode: false, aliceStatusAtTime: "listening", source: "chat" }];

function useAliceSession(systemPrompt: string) {
  const [turns, setTurns] = useState<Turn[]>(() => { try { const saved = localStorage.getItem(STORAGE_KEY); return saved ? JSON.parse(saved).turns ?? seed : seed; } catch { return seed; } });
  const [status, setStatus] = useState<AliceStatus>("listening");
  const [voiceOn, setVoiceOn] = useState<boolean>(config.defaultVoiceOn);
  const [quietMode, setQuietMode] = useState<boolean>(config.defaultQuietMode);
  const [voiceError, setVoiceError] = useState("");
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const save = () => localStorage.setItem(STORAGE_KEY, JSON.stringify({ turns, voiceOn, quietMode, savedAt: new Date().toISOString() }));
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify({ turns, voiceOn, quietMode, savedAt: new Date().toISOString() })); }, [turns, voiceOn, quietMode]);
  const stopAudio = () => { audioRef.current?.pause(); audioRef.current = null; setStatus("listening"); };
  const playVoice = async (input: string) => {
    setVoiceError(""); setStatus("loading");
    try {
      const audio = await fetch("/api/tts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ input, voice: config.voiceName, instructions: input.length < 180 ? config.shortTtsInstructions : config.ttsInstructions, responseFormat: config.responseFormat }) });
      if (!audio.ok) throw new Error("Alice voice is temporarily unavailable.");
      const url = URL.createObjectURL(await audio.blob()); const player = new Audio(url); player.playbackRate = config.playbackRate; audioRef.current = player;
      player.onplaying = () => setStatus("speaking");
      player.onended = () => { URL.revokeObjectURL(url); audioRef.current = null; setStatus("listening"); };
      player.onerror = () => { URL.revokeObjectURL(url); audioRef.current = null; setVoiceError("Alice voice couldn't play, but her response is still here."); setStatus("listening"); };
      await player.play();
    } catch { setVoiceError("Alice voice is temporarily unavailable. You can continue in text."); setStatus("listening"); }
  };
  const send = async (text: string, inputMode: "typed" | "voice", edited = false) => {
    const userTurn: Turn = { id: crypto.randomUUID(), role: "participant", text, timestamp: now(), inputMode, transcriptEdited: edited, aliceVoiceEnabled: voiceOn, quietMode, aliceStatusAtTime: "listening", source: "chat" };
    const next = [...turns, userTurn]; setTurns(next); setStatus("thinking");
    let reply = "Thank you for sharing that. What did that experience teach you about yourself?";
    try {
      const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ system: systemPrompt, messages: next.filter(t => t.role !== "system").map(t => ({ role: t.role === "participant" ? "user" : "assistant", content: t.text })) }) });
      if (response.ok) reply = (await response.json()).reply || reply;
    } catch { /* preserve a natural offline fallback */ }
    const aliceTurn: Turn = { id: crypto.randomUUID(), role: "alice", text: reply, timestamp: now(), inputMode, transcriptEdited: false, aliceVoiceEnabled: voiceOn, quietMode, aliceStatusAtTime: quietMode || !voiceOn ? "thinking" : "speaking", source: "chat" };
    setTurns(current => [...current, aliceTurn]);
    if (voiceOn && !quietMode) await playVoice(reply); else setStatus("listening");
  };
  return { turns, setTurns, status, setStatus, voiceOn, setVoiceOn, quietMode, setQuietMode, voiceError, setVoiceError, playVoice, save, stopAudio, send };
}

const Card = ({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) => <section className={`rail-card ${className}`}><h2>{title}</h2>{children}</section>;
const PlaceholderButton = ({ children, onClick }: { children: React.ReactNode; onClick?: () => void }) => <button className="outline-button" onClick={onClick}>{children}</button>;

export default function DiscoveryPage() {
  const [promptProfileId, setPromptProfileId] = useState<AlicePromptProfileId>(() => { const saved = localStorage.getItem(PROMPT_PROFILE_STORAGE_KEY); return isAlicePromptProfileId(saved) ? saved : config.defaultAlicePromptProfileId; });
  const activePromptProfile = useMemo(() => getAlicePromptProfile(promptProfileId), [promptProfileId]);
  const session = useAliceSession(activePromptProfile.systemPrompt);
  const [theme, setTheme] = useState<"dark" | "light">(() => localStorage.getItem("lighthouse.discovery.theme") === "light" ? "light" : "dark");
  const [tab, setTab] = useState<Tab>("speak"); const [typed, setTyped] = useState(""); const [recording, setRecording] = useState(false); const [paused, setPaused] = useState(false); const [seconds, setSeconds] = useState(0); const [review, setReview] = useState(""); const [originalReview, setOriginalReview] = useState("");
  const [modal, setModal] = useState<"transcript" | "placeholder" | "delete" | null>(null); const [placeholder, setPlaceholder] = useState(""); const [mobileRail, setMobileRail] = useState<"left" | "right" | null>(null); const [sessionPaused, setSessionPaused] = useState(false);
  const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]); const chatTop = useRef<HTMLDivElement | null>(null);
  const visibleTurns = useMemo(() => [...session.turns].reverse(), [session.turns]);
  useEffect(() => { chatTop.current?.scrollIntoView({ behavior: "smooth", block: "nearest" }); }, [session.turns.length]);
  useEffect(() => { if (!recording || paused) return; const id = window.setInterval(() => setSeconds(s => s + 1), 1000); return () => clearInterval(id); }, [recording, paused]);
  const openPlaceholder = (name: string) => { setPlaceholder(name); setModal("placeholder"); };
  const startRecording = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const r = new MediaRecorder(stream); chunks.current = []; r.ondataavailable = e => chunks.current.push(e.data); r.start(); recorder.current = r; setRecording(true); setPaused(false); setSeconds(0); session.setStatus("listening"); } catch { openPlaceholder("Microphone access is unavailable. Check your browser permission, or use Type Instead."); } };
  const finishRecording = () => { const r = recorder.current; if (!r) return; r.onstop = async () => { r.stream.getTracks().forEach(t => t.stop()); setRecording(false); setPaused(false); session.setStatus("loading"); const blob = new Blob(chunks.current, { type: r.mimeType || "audio/webm" }); try { const form = new FormData(); form.append("file", blob, "answer.webm"); form.append("model", config.transcriptionModel); const response = await fetch("/api/transcribe", { method: "POST", body: form }); if (!response.ok) throw new Error(); const text = (await response.json()).text || ""; setReview(text); setOriginalReview(text); } catch { setReview("Your recording is ready. Transcription needs a configured server connection; you can type or edit your answer here."); setOriginalReview(""); } finally { session.setStatus("listening"); } }; r.stop(); };
  const cancelRecording = () => { recorder.current?.stop(); recorder.current?.stream.getTracks().forEach(t => t.stop()); setRecording(false); setPaused(false); setSeconds(0); session.setStatus("listening"); };
  const sendText = async () => { const value = typed.trim(); if (!value) return; setTyped(""); await session.send(value, "typed"); };
  const sendReview = async () => { const value = review.trim(); if (!value) return; const edited = value !== originalReview; setReview(""); await session.send(value, "voice", edited); };
  const exportTranscript = () => { const content = session.turns.map(t => `[${t.timestamp}] ${t.role === "participant" ? "You" : "Alice"}: ${t.text}`).join("\n\n"); const url = URL.createObjectURL(new Blob([content], { type: "text/plain" })); const a = document.createElement("a"); a.href = url; a.download = "lighthouse-discovery-transcript.txt"; a.click(); URL.revokeObjectURL(url); };
  const clearData = () => { session.stopAudio(); session.setTurns(seed); localStorage.removeItem(STORAGE_KEY); setModal(null); };
  const toggleVoice = () => { const next = !session.voiceOn; session.setVoiceOn(next); session.setQuietMode(!next); if (!next) session.stopAudio(); };
  const toggleTheme = () => { const next = theme === "dark" ? "light" : "dark"; setTheme(next); localStorage.setItem("lighthouse.discovery.theme", next); };
  const selectPromptProfile = (id: AlicePromptProfileId) => { setPromptProfileId(id); localStorage.setItem(PROMPT_PROFILE_STORAGE_KEY, id); };
  const showPromptProfileSelector = import.meta.env.DEV || import.meta.env.VITE_SHOW_ALICE_PROMPT_SELECTOR === "true";
  const elapsed = useMemo(() => `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`, [seconds]);
  return <div className={`discovery-page discovery-page--${theme}`}>
    <header className="topbar"><button className="icon-button mobile-menu" onClick={() => setMobileRail("left")} aria-label="Open progress menu"><Menu /></button><div className="brand"><img className="brand-medallion" src="/lighthouse-medallion.png" alt="Lighthouse"/><span>LIGHTHOUSE<small>Human Insight. Real Connection.</small></span></div><div className="page-title"><strong>LIGHTHOUSE DISCOVERY ENGINE</strong><small>You guide the conversation. <b>Alice</b> helps you be fully seen.</small></div><div className="top-actions"><span className="session-pill"><small>Session Status</small><b>● &nbsp; In Progress</b></span><button className="top-action-button save-exit-button" onClick={() => { session.save(); openPlaceholder("Progress saved on this device."); }}>Save & Exit</button><button className="top-action-button icon-button theme-toggle" onClick={toggleTheme} aria-label={`Use ${theme === "dark" ? "light" : "dark"} theme`}>{theme === "dark" ? <Sun/> : <Moon/>}</button><button className="top-action-button icon-button" aria-label="Notifications"><Bell /></button><button className="top-action-button profile-button" aria-label="Open profile menu"><span>E</span><ChevronDown/></button></div><button className="icon-button mobile-menu" onClick={() => setMobileRail("right")} aria-label="Open insights menu"><Sparkles /></button></header>
    <main className="three-column">
      <aside className={`left-rail ${mobileRail === "left" ? "rail-open" : ""}`}><button className="drawer-close" onClick={() => setMobileRail(null)}><X /></button>
        <Card title="DISCOVERY PROGRESS"><div className="progress-ring"><span>42<small>%</small></span></div><div className="progress-copy"><b>Building Your Profile</b><span>Strong Foundation</span></div><ol className="steps">{[["Discover","Conversations & Insights"],["Understand","Patterns & Themes"],["Shape","Your Profile"],["Confirm","You're in Control"],["Connect","When You're Ready"]].map((s,i)=><li className={i===0?"active":""} key={s[0]}><i>{i===0?<Sparkles/>:<span>{i+1}</span>}</i><b>{s[0]}<small>{s[1]}</small></b></li>)}</ol></Card>
        <Card title="YOUR CONTROL CENTER"><Info icon={<Sparkles/>} title="You steer this process." text="Share what matters, skip what doesn't."/><Info icon={<Pause/>} title="You can pause anytime." text="Your information is always saved."/><Info icon={<Check/>} title="You decide what goes in." text="Nothing is added without you."/><Info icon={<ShieldCheck/>} title="You review before anything is used." text="Always."/></Card>
        <Card title="SESSION INFO"><dl className="session-info"><div><dt>◷ &nbsp; Started</dt><dd>Today, {seed[0].timestamp}</dd></div><div><dt>◷ &nbsp; Time Together</dt><dd>48 min</dd></div><div><dt>▣ &nbsp; Conversations</dt><dd>{session.turns.length}</dd></div><div><dt>▤ &nbsp; Last Saved</dt><dd>just now</dd></div></dl><PlaceholderButton onClick={() => setModal("transcript")}>View Full Transcript</PlaceholderButton></Card>
        <Card title="NEED A BREAK?"><Info icon={<Pause/>} title="Pause Discovery." text="We'll save everything."/><PlaceholderButton onClick={() => { setSessionPaused(!sessionPaused); session.stopAudio(); session.save(); }}>{sessionPaused ? "Resume Session" : "Pause Session"}</PlaceholderButton></Card>
      </aside>
      <section className="center-panel"><div className="discovery-console"><div className="alice-identity"><AliceAvatar status={session.status} size="lg"/><h1>Alice <Sparkles/></h1><b>Your Discovery Guide</b><button className={`voice-mode-button ${session.voiceOn?"active":""}`} onClick={toggleVoice} aria-pressed={session.voiceOn}><Volume2/> Voice {session.voiceOn?"On":"Off"}</button><span className={`alice-debug alice-debug--${session.status}`}>Alice status: {session.status}{showPromptProfileSelector ? ` · ${activePromptProfile.name}` : ""}</span>{showPromptProfileSelector && <label className="prompt-mode-control">Alice Prompt Mode<select value={promptProfileId} onChange={event=>selectPromptProfile(event.target.value as AlicePromptProfileId)}>{alicePromptProfiles.map(profile=><option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label>}</div>
        <div className="composer"><div className="tabs"><button className={tab==="speak"?"active":""} onClick={()=>setTab("speak")}><Mic/> Speak Your Answer</button><button className={tab==="type"?"active":""} onClick={()=>setTab("type")}><FileText/> Type Instead</button><button className={tab==="attach"?"active":""} onClick={()=>setTab("attach")}><Paperclip/> Attach (Optional)</button></div>
          {tab === "speak" && <div className="speak-pane"><b>Push to Talk</b><small>Tap to record. Review before Alice responds.</small><div className="record-line"><AliceStatusWaveform status={recording&&!paused?"listening":"loading"}/><button className={`record-button ${recording?"recording":""}`} onClick={recording?finishRecording:startRecording} aria-label={recording?"Done speaking":"Start recording"}>{recording?<Square/>:<Mic/>}</button><AliceStatusWaveform status={recording&&!paused?"listening":"loading"}/></div><strong>{elapsed}</strong><span>{recording ? paused ? "Recording paused" : "Listening..." : "Ready to record"}</span><div className="record-actions"><button disabled={!recording} onClick={()=>{ if(!recorder.current)return; if (paused) recorder.current.resume(); else recorder.current.pause(); setPaused(!paused); }}>{paused?<Play/>:<Pause/>} {paused?"Resume":"Pause"}</button><button disabled={!recording} onClick={finishRecording}><Check/> Done Speaking</button><button disabled={!recording} onClick={cancelRecording}><X/> Cancel</button></div></div>}
          {tab === "type" && <div className="type-pane"><textarea value={typed} onChange={e=>setTyped(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault(); void sendText();}}} placeholder="Share what’s on your mind…"/><button onClick={sendText} disabled={!typed.trim()}><Send/> Send to Alice</button></div>}
          {tab === "attach" && <div className="attach-pane"><Paperclip/><b>Attach context later</b><span>Coming soon — attachments are not processed in Run 1.</span></div>}
        </div></div>
        <div className="transcript-review"><div><b>Your Transcript <span>(Review before sending)</span></b><label><FileText/> Edit</label></div><textarea value={review} onChange={e=>setReview(e.target.value)} placeholder="Your recorded transcript will appear here for review."/><button onClick={sendReview} disabled={!review.trim()}><Send/> Send to Alice</button></div>
        <div className="voice-error-slot">{session.voiceError && <div className="voice-error" role="status"><Speaker/> {session.voiceError}<button onClick={()=>session.setVoiceError("")}><X/></button></div>}</div>
        <div className="conversation-divider"><span>Conversation</span><i /></div>
        <div className="chat"><div ref={chatTop}/>{visibleTurns.map(turn => <div className={`message-row message-row--${turn.role}`} key={turn.id}>{turn.role === "alice" && <AliceAvatar status={turn.aliceStatusAtTime} size="sm"/>}<div className="bubble"><time>{turn.timestamp}</time><p>{turn.text}</p>{turn.role === "alice" && turn.aliceVoiceEnabled && <Volume2 className="bubble-speaker"/>}</div>{turn.role === "participant" && <span className="user-dot">E</span>}</div>)}</div>
      </section>
      <aside className={`right-rail ${mobileRail === "right" ? "rail-open" : ""}`}><button className="drawer-close" onClick={() => setMobileRail(null)}><X /></button>
        <Card title="DISCOVERY INSIGHTS (Preview)"><h3>Emerging Themes</h3>{[["Resilience",88,"Strong Signal"],["Responsibility",82,"Strong Signal"],["Empathy",65,"Moderate Signal"],["Growth",65,"Moderate Signal"],["Independence",43,"Early Signal"]].map((x,i)=><div className={`signal signal-${i}`} key={x[0] as string}><span><Sparkles/><b>{x[0]}</b><small>{x[2]}</small></span><i><em style={{width:`${x[1]}%`}}/></i></div>)}<PlaceholderButton onClick={()=>openPlaceholder("Insights are a preview in Run 1.")}>Explore Insights</PlaceholderButton></Card>
        <Card title="WHAT ALICE IS LEARNING"><Info icon={<Heart/>} title="What matters to you" text="Your values and priorities"/><Info icon={<Brain/>} title="How you think" text="Your perspective and patterns"/><Info icon={<Zap/>} title="What drives you" text="Your motivations and energy"/><Info icon={<CircleUserRound/>} title="How you contribute" text="Your unique strengths"/><PlaceholderButton onClick={()=>openPlaceholder("The Learning Map is coming soon.")}>View Learning Map</PlaceholderButton></Card>
        <Card title="PRIVACY & TRUST"><Info icon={<ShieldCheck/>} title="Your data is yours." text="We never sell your information."/><Info icon={<ShieldCheck/>} title="Private by default." text="You choose what to share."/><Info icon={<ShieldCheck/>} title="Secure & encrypted." text="Your privacy is protected."/><PlaceholderButton onClick={()=>openPlaceholder("Privacy details are coming soon.")}>Learn More</PlaceholderButton></Card>
        <Card title="QUICK ACTIONS"><div className="quick-actions"><button onClick={()=>openPlaceholder("Insights review is coming soon.")}><FileText/>Review My Insights</button><button onClick={()=>openPlaceholder("Preferences are coming soon.")}><Check/>Update My Preferences</button><button onClick={exportTranscript}><Download/>Export My Transcript</button><button onClick={()=>setModal("delete")}><Trash2/>Delete My Data</button></div></Card>
      </aside>
    </main>
    <footer className="bottom-bar"><div><h3>VOICE & AUDIO</h3><button className={session.voiceOn?"footer-voice-active":""} onClick={toggleVoice}><Volume2/> Voice <b>{session.voiceOn?"On":"Off"}</b></button></div><div><h3>SESSION SHORTCUTS</h3><span className="shortcut-grid"><button onClick={()=>{session.save();openPlaceholder("Progress saved on this device.")}}>Save Progress</button><button onClick={()=>openPlaceholder("Notes are coming soon.")}>Add Note</button><button onClick={()=>setTab("type")}>Ask Alice Anything</button><button onClick={()=>openPlaceholder("Topic navigation is coming soon.")}>Jump to Topic</button></span></div><div className="next"><h3>WHAT HAPPENS NEXT?</h3><p>When you feel ready, you can turn your insights into a complete profile and choose opportunities that fit you.</p><button onClick={()=>openPlaceholder("Snapshot Profile generation is separate from live Discovery and is coming soon.")}>Generate Snapshot Profile →</button></div><div><h3>ALICE STATUS LEGEND</h3><AliceStatusLegend/></div></footer>
    {modal && <div className="modal-backdrop" onMouseDown={()=>setModal(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setModal(null)}><X/></button>{modal==="transcript"&&<><h2>Full Transcript</h2><div className="full-transcript">{session.turns.map(t=><p key={t.id}><b>{t.role==="participant"?"You":"Alice"}</b><time>{t.timestamp}</time>{t.text}</p>)}</div><button className="primary" onClick={exportTranscript}><Download/> Export Transcript</button></>}{modal==="placeholder"&&<><Lightbulb className="modal-icon"/><h2>{placeholder}</h2><p>This space is intentionally light in the Run 1 baseline.</p><button className="primary" onClick={()=>setModal(null)}>Got it</button></>}{modal==="delete"&&<><Trash2 className="modal-icon danger"/><h2>Delete local Discovery data?</h2><p>This clears the transcript saved in this browser. This cannot be undone.</p><div className="modal-actions"><button onClick={()=>setModal(null)}>Cancel</button><button className="danger-button" onClick={clearData}>Delete My Data</button></div></>}</div></div>}
  </div>;
}

function Info({icon,title,text}:{icon:React.ReactNode;title:string;text:string}) { return <div className="info-row"><i>{icon}</i><span><b>{title}</b><small>{text}</small></span></div>; }
